### ISSUE TITLE
The login email and password are unknown

### ISSUE THREAD

**Issue by mohammedazan** [LilyMilano/employee-management-system-Laravel-Dec0122#1]
http://127.0.0.1:8080/login#
I want to access the application, but I couldn't find the password and email. Please guide me to them

**Comment by LilyMilano** [comment]
Hello, thank you for your interest. I have added the new user registration functionality so you can log in. Since it was a small application, I had disabled it. 

You can register a new user or log in with this test data:
Email: pin2203.g4@gmail.com
Password: test1234

If you register a new user, the login data is stored with the 'hidden' property in the 'users' table migrated to the database.

I hope this is helpful and I am still available if you require additional information. Best regards!

![activate_register_form](https://github.com/LilyMilano/employee-management-system-Laravel-Dec0122/assets/107228065/683c9936-33a5-45ac-b4bc-348719e54aad)

![frontend-form](https://github.com/LilyMilano/employee-management-system-Laravel-Dec0122/assets/107228065/8090cd53-a4f0-4c9f-a85c-cd885b8f8d83)

**Comment by mohammedazan** [comment]
No, I did not encounter any other problems. Thank you for your response🙏

**Comment by LilyMilano** [comment]
> No, I did not encounter any other problems. Thank you for your response🙏

🙏
